### ISSUE TITLE
Production config error 

### ISSUE THREAD

**Issue by manosbatsis** [jakejarrett/turbo-couscous#1]
```
$  webpack --config webpack.production.config.js
/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/ParsePlugin.js:22
			if(parsed.module)
			         ^

TypeError: Cannot read property 'module' of null
    at Resolver.<anonymous> (/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/ParsePlugin.js:22:13)
    at Resolver.applyPluginsParallelBailResult1 (/home/manos/foobar/turbo-couscous/node_modules/tapable/lib/Tapable.js:215:14)
    at beforeInnerCallback (/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/Resolver.js:112:19)
    at loggingCallbackWrapper (/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/home/manos/foobar/turbo-couscous/node_modules/tapable/lib/Tapable.js:108:46)
    at Resolver.doResolve (/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/Resolver.js:100:11)
    at Resolver.<anonymous> (/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:36:12)
    at Resolver.applyPluginsParallelBailResult1 (/home/manos/foobar/turbo-couscous/node_modules/tapable/lib/Tapable.js:215:14)
    at beforeInnerCallback (/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/Resolver.js:112:19)
    at loggingCallbackWrapper (/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/home/manos/foobar/turbo-couscous/node_modules/tapable/lib/Tapable.js:108:46)
    at Resolver.doResolve (/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/Resolver.js:100:11)
    at Resolver.resolve (/home/manos/foobar/turbo-couscous/node_modules/enhanced-resolve/lib/Resolver.js:74:14)
    at /home/manos/foobar/turbo-couscous/node_modules/webpack/lib/NormalModuleFactory.js:215:12
    at /home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:355:9)
    at Object.map (/home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:337:20)
    at NormalModuleFactory.resolveRequestArray (/home/manos/foobar/turbo-couscous/node_modules/webpack/lib/NormalModuleFactory.js:214:8)
    at /home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:233:13)
    at _parallel (/home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:731:9)
    at /home/manos/foobar/turbo-couscous/node_modules/webpack/lib/NormalModuleFactory.js:154:11
    at /home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:726:13
    at /home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:52:16
    at done (/home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:246:17)
    at /home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:44:16
    at /home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:723:17
    at /home/manos/foobar/turbo-couscous/node_modules/async/lib/async.js:167:37
```

**Comment by jakejarrett** [comment]
I'll push a fix for this tonight/tomorrow, I am remember encountering this with the dev package too at one stage.

**Comment by jakejarrett** [comment]
Should be fixed with the latest push :+1:
